/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

/**
 *
 * @author User
 */
public class Item extends javax.swing.JPanel {

    /**
     * Creates new form Item
     */
    public Item( String name, String des) {
        initComponents();
        ibName.setText(name);
        ibDesc.setText(des);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ibName = new javax.swing.JLabel();
        ibDesc = new javax.swing.JLabel();

        setOpaque(false);

        ibName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ibName.setForeground(new java.awt.Color(136, 136, 136));
        ibName.setText("Name");

        ibDesc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ibDesc.setForeground(new java.awt.Color(136, 136, 136));
        ibDesc.setText("Description");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ibName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ibDesc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibName)
                    .addComponent(ibDesc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ibDesc;
    private javax.swing.JLabel ibName;
    // End of variables declaration//GEN-END:variables
}
